spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kinopoisk
    username: postgres
    password: Kirilova%618249

  liquibase:
    change-log: db/changelog/main-changelog.xml
